/* ---------- ACCESSORY CATEGORY ENUM (READ-ONLY) ---------- */

export const ACCESSORY_CATEGORIES = [
  "SPO2 PROBE",
  "MEDICAL BETTERIES",
  "CAUTERY ACCESSORIES",
  "VENTILATOR ACCESSORIES",
  "VENTILATOR CIRCUIT",
  "FLOW/OXYGEN SENSOR",
  "KEY PAD",
  "WARMER & MONITOR TEMP SENSOR",
  "HUMIDIFIER TEAMPERATURE SENSOR",
  "NIBP ACCESSORIES",
  "IBP CABLE",
  "IBP TRANSDUCER KIT",
  "ECG CLAMP/BULB & ROLL",
  "3/5 LEAD EGG CABLE",
  "10 LEAD ECG CABLE",
  "AVAILABLE FOR",
] as const;

/* ---------- TYPE DERIVED FROM ENUM ---------- */
export type AccessoryCategory =
  (typeof ACCESSORY_CATEGORIES)[number];
