import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";
import { Providers } from "@/providers/providers";
import Navbar from "@/components/navbar"; // <-- Import your navbar here
import Footer from "@/components/footer"; // <-- Import your footer here

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Providers>
          {/* Add navbar above page content */}
          <Navbar />

          {/* Add some top padding to prevent content being hidden under fixed navbar */}
          <main>
            {children}
          </main>

          {/* Footer at the bottom */}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
